export enum ProjectPermissionSet {
    "CREATE" = "createProject",
    "UPDATE" = "updateProject",
    "UPDATE_PROJECT_MEMBERS" = "modifyProjectMembers",
    "UPLOAD_PROJECT_FILES" = "uploadProjectFiles",
    "DELETE_PROJECT_FILES" = "deleteProjectFiles",
    "DELETE" = "deleteProject",
    "READ" = "readProject",
    "READ_PROJECT_REPORT" = "readProjectReport",
    "REAL_ALL_PROJECT" = "readAllProject",
    "UPDATE_ANY_PROJECT" = "updateAnyProject",
    "DELETE_ANY_PROJECT" = "deleteAnyProject",
    "HOLD_UNHOLD_PROJECT" = "holdUnholdProject",
    "CHANGE_STATUS" = "changeProjectStatus",
    "READ_FINANCE_REPORT" = "readFinanceReport",
    "ADD_PROJECT_STATES" = "addProjectStates",
}